package egresspolicy

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"net/netip"
	"net/url"
	"sort"
	"strconv"
	"strings"

	"github.com/kotaru34/tethys-sentinel/internal/sshtarget"
)

const Version = "sentinel-egress-v1"

type Destination struct {
	IP    string   `json:"ip"`
	Port  uint16   `json:"port"`
	Names []string `json:"names,omitempty"`
}

type Policy struct {
	Version string        `json:"version"`
	Control Destination   `json:"control"`
	Targets []Destination `json:"targets"`
}

func Build(controlURL string, targets []sshtarget.Spec) (Policy, error) {
	control, err := parseControl(controlURL)
	if err != nil {
		return Policy{}, err
	}
	if len(targets) == 0 {
		return Policy{}, errors.New("egress policy requires at least one SSH target")
	}

	type aggregate struct {
		ip    netip.Addr
		port  uint16
		names map[string]struct{}
	}
	byEndpoint := make(map[string]*aggregate, len(targets))
	for _, target := range targets {
		name := strings.TrimSpace(target.Name)
		if !safeLabel(name) {
			return Policy{}, fmt.Errorf("invalid SSH target name %q", target.Name)
		}
		ip, port, err := parseLiteralEndpoint(target.Address)
		if err != nil {
			return Policy{}, fmt.Errorf("SSH target %q: %w", name, err)
		}
		key := net.JoinHostPort(ip.String(), strconv.Itoa(int(port)))
		agg := byEndpoint[key]
		if agg == nil {
			agg = &aggregate{ip: ip, port: port, names: make(map[string]struct{})}
			byEndpoint[key] = agg
		}
		agg.names[name] = struct{}{}
	}

	out := Policy{Version: Version, Control: control, Targets: make([]Destination, 0, len(byEndpoint))}
	for _, agg := range byEndpoint {
		names := make([]string, 0, len(agg.names))
		for name := range agg.names {
			names = append(names, name)
		}
		sort.Strings(names)
		out.Targets = append(out.Targets, Destination{IP: agg.ip.String(), Port: agg.port, Names: names})
	}
	sort.Slice(out.Targets, func(i, j int) bool {
		if out.Targets[i].IP != out.Targets[j].IP {
			return out.Targets[i].IP < out.Targets[j].IP
		}
		if out.Targets[i].Port != out.Targets[j].Port {
			return out.Targets[i].Port < out.Targets[j].Port
		}
		return strings.Join(out.Targets[i].Names, "\x00") < strings.Join(out.Targets[j].Names, "\x00")
	})
	return out, nil
}

func (p Policy) SHA256() (string, error) {
	payload, err := json.Marshal(p)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(payload)
	return hex.EncodeToString(sum[:]), nil
}

func (p Policy) JSON() ([]byte, error) {
	return json.MarshalIndent(p, "", "  ")
}

func RenderPVE(p Policy) ([]byte, error) {
	if p.Version != Version {
		return nil, fmt.Errorf("unsupported egress policy version %q", p.Version)
	}
	if _, _, err := parseLiteralDestination(p.Control); err != nil {
		return nil, fmt.Errorf("invalid control destination: %w", err)
	}
	for _, destination := range p.Targets {
		if _, _, err := parseLiteralDestination(destination); err != nil {
			return nil, fmt.Errorf("invalid target destination: %w", err)
		}
	}
	hash, err := p.SHA256()
	if err != nil {
		return nil, err
	}

	var b strings.Builder
	b.WriteString("# Generated by Tethys Sentinel. Apply on the Proxmox host, never from sentinel-worker.\n")
	b.WriteString("# policy_sha256: ")
	b.WriteString(hash)
	b.WriteString("\n\n[OPTIONS]\n\nenable: 1\npolicy_out: DROP\n\n[RULES]\n\n")
	writePVERule(&b, p.Control, "sentinel-control")
	for _, destination := range p.Targets {
		writePVERule(&b, destination, "ssh:"+strings.Join(destination.Names, ","))
	}
	return []byte(b.String()), nil
}

func parseControl(raw string) (Destination, error) {
	u, err := url.Parse(strings.TrimSpace(raw))
	if err != nil || u.Host == "" {
		return Destination{}, errors.New("control URL must be a valid HTTPS URL with a host")
	}
	if u.Scheme != "https" {
		return Destination{}, errors.New("external worker egress policy requires an HTTPS control URL")
	}
	if u.User != nil || u.RawQuery != "" || u.Fragment != "" || (u.Path != "" && u.Path != "/") {
		return Destination{}, errors.New("control URL must contain only scheme, literal host and optional port")
	}
	ip, err := netip.ParseAddr(u.Hostname())
	if err != nil || !concreteIP(ip) {
		return Destination{}, errors.New("control URL host must be a concrete literal IP; use TLS server_name separately")
	}
	port := uint16(443)
	if rawPort := u.Port(); rawPort != "" {
		value, err := strconv.Atoi(rawPort)
		if err != nil || value < 1 || value > 65535 {
			return Destination{}, errors.New("control URL has invalid port")
		}
		port = uint16(value)
	}
	return Destination{IP: ip.String(), Port: port}, nil
}

func parseLiteralEndpoint(raw string) (netip.Addr, uint16, error) {
	host, portText, err := net.SplitHostPort(strings.TrimSpace(raw))
	if err != nil {
		return netip.Addr{}, 0, errors.New("endpoint must be literal-ip:port")
	}
	ip, err := netip.ParseAddr(strings.TrimSpace(host))
	if err != nil || !concreteIP(ip) {
		return netip.Addr{}, 0, errors.New("endpoint must use a concrete literal IP")
	}
	port, err := strconv.Atoi(portText)
	if err != nil || port < 1 || port > 65535 {
		return netip.Addr{}, 0, errors.New("endpoint has invalid port")
	}
	return ip, uint16(port), nil
}

func parseLiteralDestination(destination Destination) (netip.Addr, uint16, error) {
	ip, err := netip.ParseAddr(strings.TrimSpace(destination.IP))
	if err != nil || !concreteIP(ip) {
		return netip.Addr{}, 0, errors.New("destination IP must be concrete and literal")
	}
	if destination.Port == 0 {
		return netip.Addr{}, 0, errors.New("destination port must be non-zero")
	}
	for _, name := range destination.Names {
		if !safeLabel(name) {
			return netip.Addr{}, 0, fmt.Errorf("invalid destination label %q", name)
		}
	}
	return ip, destination.Port, nil
}

func concreteIP(ip netip.Addr) bool {
	return ip.IsValid() && !ip.IsUnspecified() && !ip.IsMulticast()
}

func safeLabel(value string) bool {
	if len(value) < 1 || len(value) > 128 {
		return false
	}
	for _, r := range value {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || strings.ContainsRune("._:-", r) {
			continue
		}
		return false
	}
	return true
}

func writePVERule(b *strings.Builder, destination Destination, label string) {
	b.WriteString("OUT ACCEPT -dest ")
	b.WriteString(destination.IP)
	b.WriteString(" -p tcp -dport ")
	b.WriteString(strconv.Itoa(int(destination.Port)))
	b.WriteString(" -log nolog # ")
	b.WriteString(label)
	b.WriteByte('\n')
}
