---
all:
  vars:
    sentinel_artifact_dir: "{{ inventory_dir }}/../artifacts/linux-amd64"
    sentinel_target_ssh_ca_pub_file: "{{ inventory_dir }}/../secrets/ssh-user-ca.pub"

  children:
    sentinel_targets:
      hosts:
        sentinel-target-example:
          ansible_host: 192.0.2.14
          ansible_user: operator
          sentinel_target_id: target-example
          sentinel_target_address: 192.0.2.14
          sentinel_target_role_description: example managed service host
          sentinel_target_services:
            - sshd

    sentinel_control:
      hosts:
        sentinel-control-example:
          ansible_host: 192.0.2.10
          ansible_user: operator

    sentinel_pve:
      hosts:
        pve-example:
          ansible_host: 192.0.2.100
          ansible_user: root
          sentinel_worker_vmid: 1234
          sentinel_worker_net: net0
          sentinel_control_url: https://192.0.2.10:9091
          sentinel_ntp_sources:
            - 192.0.2.1
